/*
  SOC 105 card bank
  Content is separated from the interface so instructors can revise the bank
  without changing app.js. Definitions are concise instructional paraphrases.
*/

const EXAM_INFO = {
  1: {
    title: "Exam 1: Foundations & Research",
    shortTitle: "Foundations & Research",
    description: "Think sociologically, apply the three major perspectives, and evaluate how sociologists produce evidence.",
    topics: ["Sociology and the sociological imagination", "Macro- and micro-level analysis", "Functionalism, conflict theory, and symbolic interactionism", "Research design, methods, measurement, sampling, and ethics"]
  },
  2: {
    title: "Exam 2: Culture, Socialization & Interaction",
    shortTitle: "Culture & Socialization",
    description: "Explain how culture is created, how people learn society, and how roles and meanings guide everyday interaction.",
    topics: ["Culture, values, beliefs, norms, and sanctions", "Cultural variation and cultural change", "Agents and theories of socialization", "Statuses, roles, and the social construction of reality"]
  },
  3: {
    title: "Exam 3: Groups, Organizations & Deviance",
    shortTitle: "Groups & Deviance",
    description: "Analyze group structure, formal organizations, conformity, deviance, crime, sanctions, and social control.",
    topics: ["Primary, secondary, reference, in-groups, and out-groups", "Group size, leadership, conformity, and bureaucracy", "Norms, sanctions, deviance, and social control", "Functionalist, conflict, labeling, and learning explanations of deviance"]
  },
  4: {
    title: "Exam 4: Inequality & Identity",
    shortTitle: "Inequality & Identity",
    description: "Examine stratification and inequality through social class, race and ethnicity, gender, and sexuality.",
    topics: ["Stratification systems, class, wealth, income, and mobility", "Poverty and sociological theories of inequality", "Sex, gender, sexuality, and gender socialization", "Race, ethnicity, prejudice, discrimination, racism, and intergroup relations"]
  },
  5: {
    title: "Exam 5: Social Institutions",
    shortTitle: "Social Institutions",
    description: "Apply sociological concepts to government, the economy, education, religion, health, and medicine.",
    topics: ["Power, authority, government, and political perspectives", "Economic systems, work, globalization, and alienation", "Education and religion as social institutions", "The social construction of health, disparities, medicalization, and the sick role"]
  }
};

const c = (id, exam, lesson, term, definition, example, distractors, question = "") => ({
  id, exam, lesson, term, definition, example, distractors, question
});

const SOC105_CARDS = [
  // EXAM 1 — FOUNDATIONS AND RESEARCH
  c("e1-sociology", 1, "Lesson 1 · What Is Sociology?", "Sociology",
    "The systematic study of society, social interaction, and the patterned relationships among people and groups.",
    "Studying how school policies, neighborhood conditions, and family resources shape graduation rates.",
    ["Psychology", "Economics", "Political science"],
    "Which field systematically studies society, social interaction, and patterned group relationships?"),
  c("e1-imagination", 1, "Lesson 1 · What Is Sociology?", "Sociological imagination",
    "The ability to connect personal experiences with larger social structures and historical conditions.",
    "Instead of treating unemployment only as an individual failure, examining recession, automation, and hiring practices.",
    ["Cultural relativism", "Role strain", "Value neutrality"],
    "A student connects personal college debt to tuition policy, wages, and changes in public funding. Which concept is being used?"),
  c("e1-institution", 1, "Lesson 1 · What Is Sociology?", "Social institution",
    "An established, organized pattern of beliefs and behavior developed to meet major social needs.",
    "Education, family, government, religion, and the economy organize recurring parts of social life.",
    ["Social aggregate", "Reference group", "Counterculture"],
    "Education organizes recurring roles, rules, and practices to meet a social need. Education is therefore a what?"),
  c("e1-social-facts", 1, "Lesson 1 · What Is Sociology?", "Social facts",
    "Collective ways of acting and thinking that exist outside individuals and exert social pressure on them.",
    "Laws, money, language, and institutional rules existed before a person was born and constrain that person's choices.",
    ["Independent variables", "Personal troubles", "Latent functions"],
    "Durkheim's term for external social patterns that constrain individual behavior is what?"),
  c("e1-macro", 1, "Lesson 1 · Levels of Analysis", "Macro-level analysis",
    "Study of large-scale social structures, institutions, systems, and long-term patterns.",
    "Comparing national inequality rates or examining how the education system reproduces social class.",
    ["Micro-level analysis", "Ethnography", "Dramaturgical analysis"],
    "A researcher compares national labor systems and class inequality. Which level of analysis is primary?"),
  c("e1-micro", 1, "Lesson 1 · Levels of Analysis", "Micro-level analysis",
    "Study of small-group and face-to-face interactions through which people create shared meaning.",
    "Observing how students signal respect and negotiate roles during a group project.",
    ["Macro-level analysis", "World-systems analysis", "Demography"],
    "Observing how two strangers interpret gestures during a conversation uses which level of analysis?"),
  c("e1-functionalism", 1, "Lesson 1 · Theoretical Perspectives", "Functionalism",
    "A macro perspective that views society as interdependent parts working together to promote stability and continuity.",
    "Analyzing how schools teach skills, transmit culture, and place people into occupational roles.",
    ["Conflict theory", "Symbolic interactionism", "Labeling theory"],
    "Which perspective asks how an institution contributes to social stability and the operation of society as a whole?"),
  c("e1-conflict", 1, "Lesson 1 · Theoretical Perspectives", "Conflict theory",
    "A macro perspective emphasizing unequal resources, competing interests, power, and struggles between social groups.",
    "Examining how wealthy groups influence policy to protect advantages in income, education, or healthcare.",
    ["Functionalism", "Symbolic interactionism", "Exchange theory"],
    "Which perspective would focus most directly on who benefits from unequal access to education?"),
  c("e1-interactionism", 1, "Lesson 1 · Theoretical Perspectives", "Symbolic interactionism",
    "A micro perspective examining how people use symbols and interaction to construct meanings and social reality.",
    "Studying how clothing, tone, and labels shape the way teachers interpret a student's behavior.",
    ["Functionalism", "Conflict theory", "Modernization theory"],
    "Which perspective is most useful for studying how people create meaning through everyday interaction?"),
  c("e1-manifest", 1, "Lesson 1 · Theoretical Perspectives", "Manifest function",
    "An intended and openly recognized consequence of a social pattern or institution.",
    "A college's stated purpose of teaching knowledge and occupational skills.",
    ["Latent function", "Dysfunction", "Role conflict"],
    "The planned educational purpose of a college is which type of function?"),
  c("e1-latent", 1, "Lesson 1 · Theoretical Perspectives", "Latent function",
    "An unintended or less-recognized consequence of a social pattern or institution.",
    "College may create friendship networks or delay full-time workforce entry even though neither is its stated purpose.",
    ["Manifest function", "Dysfunction", "Social fact"],
    "Meeting a future spouse at college is an unintended institutional consequence known as what?"),
  c("e1-dysfunction", 1, "Lesson 1 · Theoretical Perspectives", "Dysfunction",
    "A consequence of a social pattern that disrupts stability or reduces a system's ability to function.",
    "Overly rigid school rules may discourage creativity or exclude students who need flexibility.",
    ["Manifest function", "Latent function", "Dynamic equilibrium"],
    "A consequence that undermines the stability or effective operation of a social system is called what?"),
  c("e1-empirical", 1, "Lesson 2 · Sociological Research", "Empirical evidence",
    "Information gained through systematic observation, measurement, or experience rather than assumption alone.",
    "Survey responses, interview transcripts, observations, and administrative records can all provide empirical evidence.",
    ["Common sense", "Value judgment", "Cultural belief"],
    "Evidence gathered by systematic observation or measurement is described as what?"),
  c("e1-hypothesis", 1, "Lesson 2 · Research Design", "Hypothesis",
    "A testable statement predicting a relationship between variables.",
    "Students who work more than 30 hours per week will, on average, report less study time.",
    ["Theory", "Operational definition", "Research population"],
    "A testable prediction about the relationship between work hours and study time is a what?"),
  c("e1-independent", 1, "Lesson 2 · Research Design", "Independent variable",
    "The variable treated as the possible cause or predictor in a hypothesized relationship.",
    "In a study of whether work hours affect study time, weekly work hours are the independent variable.",
    ["Dependent variable", "Control group", "Sample"],
    "A study asks whether weekly work hours influence GPA. Weekly work hours are which kind of variable?"),
  c("e1-dependent", 1, "Lesson 2 · Research Design", "Dependent variable",
    "The outcome a researcher expects may change in response to another variable.",
    "In a study of whether work hours affect GPA, GPA is the dependent variable.",
    ["Independent variable", "Research population", "Operational definition"],
    "A study asks whether weekly work hours influence GPA. GPA is which kind of variable?"),
  c("e1-operational", 1, "Lesson 2 · Measurement", "Operational definition",
    "A precise statement of how a concept will be observed or measured in a study.",
    "Defining academic success as cumulative GPA makes the concept measurable.",
    ["Hypothesis", "Random sample", "Correlation"],
    "A researcher defines social class using annual household income and education. This is an example of what?"),
  c("e1-reliability", 1, "Lesson 2 · Measurement", "Reliability",
    "The degree to which a measure produces consistent results under consistent conditions.",
    "A scale that reports nearly the same weight when the same object is measured repeatedly is reliable.",
    ["Validity", "Generalizability", "Value neutrality"],
    "A measure gives consistent results when repeated. Which quality does it demonstrate?"),
  c("e1-validity", 1, "Lesson 2 · Measurement", "Validity",
    "The degree to which a measure actually captures the concept it claims to measure.",
    "A test of sociological understanding should measure application of sociology, not merely reading speed.",
    ["Reliability", "Randomization", "Replication"],
    "A survey item accurately measures the concept the researcher intended. Which quality does it demonstrate?"),
  c("e1-population", 1, "Lesson 2 · Sampling", "Population",
    "The complete group about which a researcher wants to draw conclusions.",
    "If the study concerns all Cincinnati State students, all enrolled students form the population.",
    ["Sample", "Control group", "Case study"],
    "All people a researcher ultimately wants to understand are collectively called the what?"),
  c("e1-sample", 1, "Lesson 2 · Sampling", "Sample",
    "A subset of a larger population selected for direct study.",
    "Surveying 400 students to learn about the experiences of the full student body uses a sample.",
    ["Population", "Variable", "Experiment"],
    "The smaller group actually surveyed from a much larger student body is the what?"),
  c("e1-random-sample", 1, "Lesson 2 · Sampling", "Random sample",
    "A sampling approach in which each population member has a known, usually equal, chance of selection.",
    "Using a random-number process to select names from a complete enrollment list.",
    ["Convenience sample", "Snowball sample", "Case study"],
    "Which sampling method gives every member of the population an equal chance to be chosen?"),
  c("e1-quantitative", 1, "Lesson 2 · Research Methods", "Quantitative data",
    "Information expressed numerically and analyzed for amounts, patterns, or statistical relationships.",
    "Counts, percentages, scale scores, ages, and income values are quantitative data.",
    ["Qualitative data", "Field notes", "Open-ended narratives"],
    "A dataset of ages, incomes, and test scores is primarily what type of data?"),
  c("e1-qualitative", 1, "Lesson 2 · Research Methods", "Qualitative data",
    "Detailed, nonnumeric information used to understand meanings, experiences, and social processes.",
    "Interview narratives and observation notes can reveal how residents interpret neighborhood change.",
    ["Quantitative data", "Experimental controls", "Statistical variables"],
    "Interview transcripts about how people interpret an experience are primarily what type of data?"),
  c("e1-survey", 1, "Lesson 2 · Research Methods", "Survey",
    "A method that gathers responses from people through standardized questions.",
    "A questionnaire asks 800 students the same questions about belonging and campus experience.",
    ["Experiment", "Ethnography", "Secondary data analysis"],
    "Which method efficiently collects standardized self-reports from a large number of respondents?"),
  c("e1-field", 1, "Lesson 2 · Research Methods", "Field research",
    "Direct observation and study of social life in its natural setting.",
    "A researcher spends months observing routines and interactions in a neighborhood organization.",
    ["Laboratory experiment", "Content analysis", "Survey"],
    "A sociologist observes people in the setting where their ordinary interaction occurs. Which method is this?"),
  c("e1-experiment", 1, "Lesson 2 · Research Methods", "Experiment",
    "A controlled method used to test causal effects by manipulating a variable and comparing outcomes.",
    "Participants are randomly assigned to receive different information before their attitudes are measured.",
    ["Survey", "Ethnography", "Secondary data analysis"],
    "Which method is best designed to isolate a causal effect through manipulation and comparison?"),
  c("e1-secondary", 1, "Lesson 2 · Research Methods", "Secondary data analysis",
    "Analysis of information that was previously collected by another person or organization.",
    "Using Census records or an existing national survey to investigate a new research question.",
    ["Participant observation", "Experiment", "Focus group"],
    "A sociologist analyzes previously collected Census data. Which method is being used?"),
  c("e1-correlation", 1, "Lesson 2 · Interpreting Evidence", "Correlation does not prove causation",
    "When two variables change together, the relationship alone does not establish that one produced the other.",
    "Ice-cream sales and swimming injuries both rise in summer because warm weather influences both.",
    ["Reliability guarantees validity", "Samples equal populations", "Experiments cannot test causes"],
    "Two variables are statistically related, but a third factor may explain both. Which research caution applies?"),
  c("e1-ethics", 1, "Lesson 2 · Research Ethics", "Informed consent",
    "A participant's voluntary agreement after receiving understandable information about the study, its demands, and foreseeable risks.",
    "Before an interview, a researcher explains confidentiality, possible discomfort, and the right to stop.",
    ["Value neutrality", "Debriefing only", "Random assignment"],
    "Participants agree voluntarily after learning what a study involves and what risks it may carry. What is this called?"),

  // EXAM 2 — CULTURE, SOCIALIZATION, AND INTERACTION
  c("e2-culture", 2, "Lesson 1 · Culture", "Culture",
    "A group's shared practices, values, beliefs, norms, symbols, and material objects.",
    "Language, holiday practices, expectations about politeness, music, and technology all form parts of culture.",
    ["Society", "Social structure", "Biology"],
    "The shared beliefs, practices, symbols, norms, and objects of a group collectively form its what?"),
  c("e2-material", 2, "Lesson 1 · Culture", "Material culture",
    "The physical objects and technologies that people create and attach meaning to.",
    "Phones, clothing, buildings, tools, and works of art are forms of material culture.",
    ["Nonmaterial culture", "Cultural universal", "Folkway"],
    "Buildings, clothing, and smartphones belong to which part of culture?"),
  c("e2-nonmaterial", 2, "Lesson 1 · Culture", "Nonmaterial culture",
    "A society's ideas and shared ways of thinking, including beliefs, values, norms, and language.",
    "Ideas about fairness and expectations concerning respectful behavior are nonmaterial.",
    ["Material culture", "Technology", "Artifacts"],
    "Beliefs about fairness and expectations for respectful behavior are examples of what?"),
  c("e2-values", 2, "Lesson 1 · Elements of Culture", "Values",
    "Broad cultural standards used to judge what is good, desirable, important, or morally appropriate.",
    "A society may emphasize individual freedom, achievement, equality, or community responsibility.",
    ["Beliefs", "Norms", "Sanctions"],
    "A culture's broad ideas about what is desirable and worthwhile are called what?"),
  c("e2-beliefs", 2, "Lesson 1 · Elements of Culture", "Beliefs",
    "Specific ideas that people accept as true about how the world works.",
    "A person may believe that hard work usually leads to success because the culture supports that claim.",
    ["Values", "Norms", "Symbols"],
    "Ideas that members of a culture accept as true are called what?"),
  c("e2-norms", 2, "Lesson 1 · Elements of Culture", "Norms",
    "Shared rules and expectations that guide behavior in particular situations.",
    "People generally lower their voices in a library and take turns in a checkout line.",
    ["Values", "Beliefs", "Statuses"],
    "Shared expectations about how people should behave in a situation are called what?"),
  c("e2-folkways", 2, "Lesson 1 · Elements of Culture", "Folkways",
    "Everyday norms of etiquette whose violation usually produces mild disapproval rather than severe punishment.",
    "Wearing noticeably inappropriate clothing to a casual event may draw stares but not legal punishment.",
    ["Mores", "Laws", "Taboos"],
    "Which kind of norm governs ordinary etiquette and usually carries mild sanctions?"),
  c("e2-mores", 2, "Lesson 1 · Elements of Culture", "Mores",
    "Norms tied to a society's moral judgments; violations are treated as seriously wrong.",
    "Rules against exploiting vulnerable people carry stronger moral weight than table manners.",
    ["Folkways", "Fashion", "Cultural lag"],
    "A norm considered central to a society's moral standards is known as what?"),
  c("e2-sanctions", 2, "Lesson 1 · Elements of Culture", "Sanctions",
    "Social rewards or penalties used to encourage conformity to norms.",
    "Praise for helping a classmate is positive; a fine for illegal parking is negative and formal.",
    ["Values", "Roles", "Beliefs"],
    "Praise, ridicule, fines, and awards are all examples of what?"),
  c("e2-ideal-real", 2, "Lesson 1 · Elements of Culture", "Ideal culture vs. real culture",
    "Ideal culture states the values and behavior a society claims to follow; real culture describes what people actually do.",
    "A society may publicly value equal opportunity while access to good schools remains unequal.",
    ["Material vs. nonmaterial culture", "High vs. popular culture", "Culture vs. society"],
    "The gap between proclaimed equality and unequal practice illustrates which distinction?"),
  c("e2-ethnocentrism", 2, "Lesson 1 · Cultural Difference", "Ethnocentrism",
    "Judging another culture by the standards of one's own culture, often assuming one's own way is superior.",
    "Calling an unfamiliar eating practice uncivilized simply because it differs from one's own customs.",
    ["Cultural relativism", "Xenocentrism", "Culture shock"],
    "A traveler judges another culture as inferior because its customs differ from home. Which concept applies?"),
  c("e2-relativism", 2, "Lesson 1 · Cultural Difference", "Cultural relativism",
    "Evaluating a cultural practice within the values, history, and social setting of that culture.",
    "A researcher seeks to understand why a ritual makes sense to community members before evaluating it.",
    ["Ethnocentrism", "Xenocentrism", "Assimilation"],
    "Trying to understand a practice using the culture's own context demonstrates what?"),
  c("e2-subculture", 2, "Lesson 1 · Cultural Variation", "Subculture",
    "A group that shares distinctive norms, values, or practices while still participating in the larger society.",
    "Skateboarders may share language, styles, and routines while remaining part of the broader culture.",
    ["Counterculture", "Dominant culture", "Social institution"],
    "A group has distinctive practices but remains connected to the larger society. It is best described as what?"),
  c("e2-counterculture", 2, "Lesson 1 · Cultural Variation", "Counterculture",
    "A group whose central values and practices deliberately oppose important elements of the dominant culture.",
    "A communal movement rejects private property and competitive individualism as organizing principles.",
    ["Subculture", "Cultural universal", "Reference group"],
    "A group deliberately rejects core values of the dominant culture. What type of culture is it?"),
  c("e2-culture-lag", 2, "Lesson 1 · Cultural Change", "Culture lag",
    "A delay in cultural adjustment when material conditions or technology change faster than norms, laws, or beliefs.",
    "AI tools develop faster than schools and workplaces can establish shared policies for their use.",
    ["Culture shock", "Diffusion", "Globalization"],
    "Technology changes faster than laws and social norms can adjust. Which concept describes this delay?"),
  c("e2-socialization", 2, "Lesson 2 · Socialization", "Socialization",
    "The lifelong process through which people learn culture, develop a self, and become able to participate in society.",
    "Children learn language and norms, while adults continue learning new workplace and family roles.",
    ["Social control", "Cultural diffusion", "Stratification"],
    "The lifelong process of learning culture and social roles is called what?"),
  c("e2-agents", 2, "Lesson 2 · Socialization", "Agents of socialization",
    "People, groups, and institutions that teach norms, values, roles, and expected behavior.",
    "Family, peers, schools, media, religion, and workplaces all socialize people.",
    ["Reference variables", "Social aggregates", "Formal sanctions"],
    "Family, peers, schools, and media are collectively known as what?"),
  c("e2-looking-glass", 2, "Lesson 2 · Theories of Self", "Looking-glass self",
    "Cooley's idea that people develop a sense of self by imagining how others perceive and judge them.",
    "A student comes to see herself as capable after repeatedly interpreting others' reactions as respectful and encouraging.",
    ["Generalized other", "Role conflict", "Self-fulfilling prophecy"],
    "Which concept explains self-development through imagined judgments reflected back by other people?"),
  c("e2-generalized-other", 2, "Lesson 2 · Theories of Self", "Generalized other",
    "Mead's term for the broad expectations and viewpoints of society that a person learns to consider.",
    "A child learns not only a parent's rule but also what people in general expect in public settings.",
    ["Significant other", "Reference group", "Out-group"],
    "A person considers the broad expectations of society rather than one specific person's reaction. Mead called this what?"),
  c("e2-i-me", 2, "Lesson 2 · Theories of Self", "Mead's “I” and “me”",
    "The “I” is the spontaneous response of the self; the “me” is the socialized self shaped by internalized expectations.",
    "Wanting to speak immediately reflects the “I”; pausing because classroom rules call for turn-taking reflects the “me.”",
    ["Id and ego", "Front stage and back stage", "Nature and nurture"],
    "In Mead's theory, which distinction contrasts the spontaneous self with the socialized self?"),
  c("e2-status", 2, "Lesson 3 · Social Interaction", "Status",
    "A socially recognized position a person occupies within a group or society.",
    "Student, parent, employee, and team captain are statuses.",
    ["Role", "Norm", "Sanction"],
    "A socially recognized position such as student or parent is a what?"),
  c("e2-ascribed", 2, "Lesson 3 · Social Interaction", "Ascribed status",
    "A social position assigned at birth or taken on involuntarily rather than earned through choice.",
    "Age, family background, and many racial classifications are commonly ascribed.",
    ["Achieved status", "Master status", "Role set"],
    "A status assigned without personal choice is classified as what?"),
  c("e2-achieved", 2, "Lesson 3 · Social Interaction", "Achieved status",
    "A social position acquired through action, effort, choice, or accomplishment.",
    "Becoming a nurse, graduate, or elected representative involves an achieved status.",
    ["Ascribed status", "Master status", "Role strain"],
    "A position gained through effort or choice is classified as what?"),
  c("e2-master", 2, "Lesson 3 · Social Interaction", "Master status",
    "A status that strongly shapes a person's identity and how others interpret nearly all of that person.",
    "A highly visible occupation or stigmatized identity may dominate how others respond to someone.",
    ["Ascribed status", "Achieved status", "Role set"],
    "Which concept describes a status that overshadows a person's other statuses?"),
  c("e2-role", 2, "Lesson 3 · Social Interaction", "Role",
    "The behavior and responsibilities expected from someone who occupies a particular status.",
    "The status of instructor carries expectations such as teaching, evaluating work, and communicating with students.",
    ["Status", "Sanction", "Value"],
    "Expected behavior attached to a social status is called a what?"),
  c("e2-role-conflict", 2, "Lesson 3 · Social Interaction", "Role conflict",
    "Tension created by incompatible expectations tied to two or more different statuses.",
    "An employee-parent must attend a required work meeting scheduled during a child's medical appointment.",
    ["Role strain", "Status inconsistency", "Role exit"],
    "Incompatible demands from the statuses of employee and parent create what?"),
  c("e2-role-strain", 2, "Lesson 3 · Social Interaction", "Role strain",
    "Tension among competing expectations within a single status.",
    "A professor must support struggling students while also enforcing the same academic standards for everyone.",
    ["Role conflict", "Master status", "Status set"],
    "Competing demands within one status create what?"),
  c("e2-thomas", 2, "Lesson 3 · Social Construction of Reality", "Thomas theorem",
    "When people define a situation as real, that definition produces real social consequences.",
    "A false rumor of a bank failure can trigger withdrawals that create an actual crisis.",
    ["Looking-glass self", "Cultural lag", "McDonaldization"],
    "A belief about a situation changes behavior and produces real consequences. Which theorem explains this?"),
  c("e2-dramaturgy", 2, "Lesson 3 · Social Interaction", "Dramaturgical analysis",
    "Goffman's approach that compares social interaction to a performance in which people manage the impressions others receive.",
    "A job applicant carefully controls clothing, language, and posture during an interview.",
    ["Conflict analysis", "Exchange theory", "Functional analysis"],
    "Comparing a job interview to a staged performance uses which approach?"),
  c("e2-impression", 2, "Lesson 3 · Social Interaction", "Impression management",
    "Efforts to influence how other people define and evaluate us during interaction.",
    "Someone removes informal photos from public view before an employer reviews a social-media profile.",
    ["Role strain", "Resocialization", "Cultural diffusion"],
    "Carefully shaping an online profile so an employer forms a desired opinion is an example of what?"),

  // EXAM 3 — GROUPS, ORGANIZATIONS, AND DEVIANCE
  c("e3-group", 3, "Lesson 1 · Groups", "Social group",
    "Two or more people who interact regularly, share expectations, and recognize a connection with one another.",
    "Members of a study team communicate, coordinate tasks, and recognize that they belong to the team.",
    ["Social aggregate", "Social category", "Crowd"],
    "People interact regularly and recognize a shared connection. Sociologically, they form what?"),
  c("e3-aggregate", 3, "Lesson 1 · Groups", "Aggregate",
    "People who happen to occupy the same place at the same time but do not necessarily interact or share identity.",
    "Strangers waiting at the same bus stop are an aggregate unless they develop ongoing interaction.",
    ["Primary group", "Reference group", "In-group"],
    "Strangers standing near one another at a bus stop are best described as what?"),
  c("e3-primary", 3, "Lesson 1 · Types of Groups", "Primary group",
    "A small group characterized by close, enduring, emotionally meaningful relationships.",
    "Close family members and long-term friends commonly form primary groups.",
    ["Secondary group", "Aggregate", "Formal organization"],
    "A small group built around intimate, lasting personal ties is what type of group?"),
  c("e3-secondary", 3, "Lesson 1 · Types of Groups", "Secondary group",
    "A larger, more impersonal group organized mainly around a specific activity or goal.",
    "A college committee may cooperate to complete work without forming close personal relationships.",
    ["Primary group", "In-group", "Reference group"],
    "A task-focused committee with impersonal relationships is what type of group?"),
  c("e3-in-group", 3, "Lesson 1 · Types of Groups", "In-group",
    "A group toward which a person feels belonging, loyalty, and a sense of “we.”",
    "Team members may define themselves as insiders and strongly support one another.",
    ["Out-group", "Aggregate", "Secondary group"],
    "A group a person identifies with and experiences as “us” is called what?"),
  c("e3-out-group", 3, "Lesson 1 · Types of Groups", "Out-group",
    "A group a person views as separate from or opposed to their own group—a social “them.”",
    "Fans may treat supporters of a rival team as an out-group.",
    ["In-group", "Primary group", "Reference group"],
    "A rival group viewed as “them” rather than “us” is called what?"),
  c("e3-reference", 3, "Lesson 1 · Types of Groups", "Reference group",
    "A group people use as a standard for evaluating themselves, their behavior, or their aspirations.",
    "A student compares study habits and career plans with those of students in a competitive professional program.",
    ["Primary group", "Aggregate", "Out-group"],
    "A person uses a professional group as a standard for self-evaluation. What kind of group is it?"),
  c("e3-dyad", 3, "Lesson 1 · Group Structure", "Dyad",
    "A two-person group; it can be intimate but is fragile because it ends if either member leaves.",
    "A friendship between two people is a dyad.",
    ["Triad", "Coalition", "Aggregate"],
    "What is the sociological term for a group containing exactly two people?"),
  c("e3-triad", 3, "Lesson 1 · Group Structure", "Triad",
    "A three-person group in which coalitions and mediation become possible, making its dynamics different from a dyad.",
    "If two members disagree, the third may mediate or align with one side.",
    ["Dyad", "Primary group", "Bureaucracy"],
    "Adding a third person makes mediation and two-against-one coalitions possible. The group is now a what?"),
  c("e3-instrumental", 3, "Lesson 1 · Leadership", "Instrumental leader",
    "A leader who concentrates on tasks, goals, schedules, and completing the group's work.",
    "During a project, one member assigns responsibilities and keeps everyone focused on the deadline.",
    ["Expressive leader", "Laissez-faire leader", "Charismatic authority"],
    "A leader keeps a group focused on tasks and deadlines. Which leadership role is this?"),
  c("e3-expressive", 3, "Lesson 1 · Leadership", "Expressive leader",
    "A leader who emphasizes group harmony, emotional support, and relationships among members.",
    "A team member reduces tension and ensures that discouraged members feel heard.",
    ["Instrumental leader", "Authoritarian leader", "Bureaucratic official"],
    "A leader concentrates on morale and group harmony. Which leadership role is this?"),
  c("e3-conformity", 3, "Lesson 1 · Group Influence", "Conformity",
    "Changing behavior or expressed beliefs to match the expectations or pressure of a group.",
    "A person gives an obviously incorrect answer after every other group member gives that answer.",
    ["Deviance", "Innovation", "Role exit"],
    "A person changes an answer to agree with unanimous group pressure. What is this?"),
  c("e3-formal-org", 3, "Lesson 1 · Organizations", "Formal organization",
    "A deliberately created, structured group designed to achieve particular goals.",
    "Colleges, corporations, hospitals, and government agencies are formal organizations.",
    ["Primary group", "Social aggregate", "Counterculture"],
    "A deliberately structured group created to accomplish specific goals is a what?"),
  c("e3-utilitarian", 3, "Lesson 1 · Organizations", "Utilitarian organization",
    "An organization people join mainly to obtain a practical or material reward.",
    "Most people participate in a workplace primarily to earn income.",
    ["Normative organization", "Coercive organization", "Primary group"],
    "A person joins an organization mainly for wages or another practical benefit. What type is it?"),
  c("e3-normative-org", 3, "Lesson 1 · Organizations", "Normative organization",
    "A voluntary organization people join to pursue shared values, interests, or socially meaningful goals.",
    "Someone volunteers with a neighborhood nonprofit because they support its mission.",
    ["Utilitarian organization", "Coercive organization", "Total institution"],
    "A person voluntarily joins a nonprofit because of commitment to its mission. What type of organization is it?"),
  c("e3-coercive", 3, "Lesson 1 · Organizations", "Coercive organization",
    "An organization whose members are forced or strongly compelled to participate, often under strict control.",
    "A prison is a coercive organization because inmates do not freely choose membership.",
    ["Normative organization", "Utilitarian organization", "Voluntary association"],
    "A prison is usually classified as which type of organization?"),
  c("e3-bureaucracy", 3, "Lesson 1 · Organizations", "Bureaucracy",
    "A formal organization organized through hierarchy, specialization, written rules, impersonality, and technical qualifications.",
    "A large agency divides labor among offices, follows written procedures, and ranks positions by authority.",
    ["Primary group", "Counterculture", "Mechanical solidarity"],
    "Hierarchy, specialized offices, written rules, and impersonality are features of what?"),
  c("e3-mcdonaldization", 3, "Lesson 1 · Organizations", "McDonaldization",
    "The spread of organizational principles centered on efficiency, calculability, predictability, and control.",
    "A service is standardized so every customer receives a fast, measurable, nearly identical experience.",
    ["Globalization", "Rational choice", "Socialization"],
    "Efficiency, calculability, predictability, and control define which organizational process?"),
  c("e3-deviance", 3, "Lesson 2 · Deviance", "Deviance",
    "Behavior, belief, or appearance that violates a group's norms and attracts social reaction.",
    "The same action may be deviant in one time or place but accepted in another because norms vary.",
    ["Crime", "Conformity", "Socialization"],
    "A behavior violates a group's norms but may not violate law. It is best described as what?"),
  c("e3-social-control", 3, "Lesson 2 · Deviance", "Social control",
    "The methods a society uses to encourage conformity and discourage norm violations.",
    "Families, peers, schools, police, praise, ridicule, and laws all contribute to social control.",
    ["Socialization only", "Role conflict", "Cultural diffusion"],
    "The broad set of mechanisms that encourages conformity is called what?"),
  c("e3-strain", 3, "Lesson 2 · Theories of Deviance", "Strain theory",
    "Merton's theory that deviance can result when socially approved goals are emphasized but legitimate means are unequally available.",
    "A person accepts the goal of wealth but uses fraud because conventional opportunities seem blocked.",
    ["Labeling theory", "Differential association theory", "Control theory"],
    "A person accepts society's success goal but uses illegitimate means because legitimate opportunities are blocked. Which theory applies?"),
  c("e3-differential", 3, "Lesson 2 · Theories of Deviance", "Differential association theory",
    "The view that deviance is learned through interaction with others who transmit techniques and definitions favorable to rule-breaking.",
    "A new group member learns both how to commit fraud and how the group justifies it.",
    ["Labeling theory", "Strain theory", "Social disorganization theory"],
    "A person learns criminal techniques and justifications from close associates. Which theory explains this?"),
  c("e3-labeling", 3, "Lesson 2 · Theories of Deviance", "Labeling theory",
    "A symbolic interactionist theory emphasizing how social reactions and labels can shape identity and future behavior.",
    "Being repeatedly treated as a troublemaker may lead a person to internalize that identity.",
    ["Strain theory", "Differential association theory", "Functionalism"],
    "Which theory focuses on how being defined as deviant can influence identity and later behavior?"),
  c("e3-primary-deviance", 3, "Lesson 2 · Labeling", "Primary deviance",
    "An initial or limited norm violation that has not become central to a person's self-concept.",
    "A teenager breaks a rule once but does not think of himself as a rule-breaker.",
    ["Secondary deviance", "Retreatism", "Innovation"],
    "A rule violation occurs but does not become part of the person's identity. What is it?"),
  c("e3-secondary-deviance", 3, "Lesson 2 · Labeling", "Secondary deviance",
    "Deviance that develops after a person internalizes a deviant label and organizes behavior around it.",
    "After repeated exclusion as a delinquent, a youth accepts the identity and joins a delinquent group.",
    ["Primary deviance", "Conformity", "Ritualism"],
    "A person internalizes a deviant label and increasingly acts through that identity. What is this called?"),
  c("e3-disorganization", 3, "Lesson 2 · Theories of Deviance", "Social disorganization theory",
    "The view that crime is more likely where weakened institutions and unstable community networks reduce informal social control.",
    "High turnover and limited neighborhood organizations can make coordinated supervision more difficult.",
    ["Labeling theory", "Strain theory", "Differential association theory"],
    "Which theory connects crime to weakened community institutions and informal controls?"),
  c("e3-conflict-deviance", 3, "Lesson 2 · Theories of Deviance", "Conflict view of deviance",
    "The view that powerful groups shape laws, enforcement, and definitions of deviance in ways that can protect their interests.",
    "Similar harmful acts may receive very different penalties depending on who commits them and whose interests are threatened.",
    ["Functionalist view", "Differential association", "Social bond theory"],
    "Which perspective asks how power influences what becomes illegal and whose behavior is punished?"),
  c("e3-crime", 3, "Lesson 2 · Crime", "Crime",
    "Behavior that violates formal criminal law; crime is a narrower category than deviance.",
    "Unusual clothing may be deviant without being criminal, while theft violates criminal law.",
    ["Deviance", "Stigma", "Informal sanction"],
    "Which term specifically refers to behavior that violates criminal law?"),
  c("e3-white-collar", 3, "Lesson 2 · Crime", "White-collar crime",
    "Nonviolent crime committed through a person's occupation or professional position, often for financial gain.",
    "An executive manipulates financial reports to mislead investors.",
    ["Street crime", "Corporate conformity", "Victimless crime"],
    "An executive commits fraud through an occupational position. What category of crime is this?"),

  // EXAM 4 — INEQUALITY AND IDENTITY
  c("e4-stratification", 4, "Lesson 1 · Social Stratification", "Social stratification",
    "A society's structured ranking of categories of people into unequal layers with different access to valued resources.",
    "Class systems distribute income, wealth, prestige, education, and power unequally.",
    ["Social differentiation", "Cultural diversity", "Role conflict"],
    "A durable system that ranks categories of people and distributes resources unequally is called what?"),
  c("e4-caste", 4, "Lesson 1 · Systems of Stratification", "Caste system",
    "A relatively closed stratification system in which social position is assigned at birth and mobility is highly restricted.",
    "Occupation and marriage may be strongly controlled by the social category into which a person is born.",
    ["Class system", "Meritocracy", "Open system"],
    "In which stratification system is position assigned at birth and social mobility sharply limited?"),
  c("e4-class", 4, "Lesson 1 · Systems of Stratification", "Class system",
    "A relatively open stratification system based largely on economic position, with some possibility of mobility.",
    "Education, occupation, income, and wealth influence class position, which can change over a lifetime.",
    ["Caste system", "Estate system", "Total institution"],
    "Which stratification system allows some movement and is strongly tied to economic position?"),
  c("e4-meritocracy", 4, "Lesson 1 · Systems of Stratification", "Meritocracy",
    "An ideal system in which social position and rewards are based entirely on individual ability and effort.",
    "Sociologists treat pure meritocracy as an ideal because inherited resources and unequal opportunities also shape outcomes.",
    ["Caste system", "Oligarchy", "Bureaucracy"],
    "What ideal system claims to distribute rewards solely according to ability and effort?"),
  c("e4-ses", 4, "Lesson 1 · Social Class", "Socioeconomic status (SES)",
    "A combined measure of social and economic position commonly based on income, education, and occupation.",
    "Two people with equal income may have different SES if their education and occupational prestige differ.",
    ["Wealth", "Power", "Standard of living"],
    "A measure combining income, education, and occupation is called what?"),
  c("e4-income-wealth", 4, "Lesson 1 · Social Class", "Income vs. wealth",
    "Income is money received over a period; wealth is the value of owned assets minus debts at a point in time.",
    "A household may earn a good salary but have little wealth because it owns few assets and carries substantial debt.",
    ["Power vs. authority", "Class vs. caste", "Prestige vs. status"],
    "Which distinction contrasts a flow of earnings with accumulated net assets?"),
  c("e4-mobility", 4, "Lesson 1 · Social Mobility", "Social mobility",
    "Movement of individuals or groups from one position in a stratification system to another.",
    "A person moves from a working-class childhood into a higher occupational class as an adult.",
    ["Social reproduction", "Status consistency", "Class consciousness"],
    "Movement from one social-class position to another is called what?"),
  c("e4-intergenerational", 4, "Lesson 1 · Social Mobility", "Intergenerational mobility",
    "A change in social position between one generation and another within a family.",
    "The adult child of hourly workers enters a high-status profession.",
    ["Intragenerational mobility", "Structural mobility", "Horizontal mobility"],
    "A daughter's class position differs substantially from her parents'. Which type of mobility is this?"),
  c("e4-intragenerational", 4, "Lesson 1 · Social Mobility", "Intragenerational mobility",
    "A change in one person's social position during that person's lifetime.",
    "An employee moves from an entry-level job into senior management over a career.",
    ["Intergenerational mobility", "Structural mobility", "Exchange mobility"],
    "A person's class position rises over the course of the same career. Which type of mobility is this?"),
  c("e4-absolute-poverty", 4, "Lesson 1 · Poverty", "Absolute poverty",
    "A condition in which resources are insufficient to meet basic survival needs such as food, safe water, shelter, and healthcare.",
    "A household cannot consistently obtain adequate food or safe shelter.",
    ["Relative poverty", "Subjective poverty", "Feminization of poverty"],
    "Which concept focuses on inability to meet basic survival needs?"),
  c("e4-relative-poverty", 4, "Lesson 1 · Poverty", "Relative poverty",
    "Economic disadvantage defined in comparison with the typical living standards of a particular society.",
    "A family can meet basic needs but lacks the resources needed to participate in activities considered ordinary locally.",
    ["Absolute poverty", "Extreme poverty", "Debt bondage"],
    "Poverty evaluated against a society's customary standard of living is called what?"),
  c("e4-davis-moore", 4, "Lesson 1 · Theories of Stratification", "Davis–Moore thesis",
    "A functionalist claim that unequal rewards help society motivate qualified people to fill positions considered important and difficult.",
    "Higher rewards are said to encourage people to complete demanding training for specialized roles.",
    ["Conflict theory", "Symbolic interactionism", "World-systems theory"],
    "Which thesis argues that unequal rewards motivate people to train for socially important positions?"),
  c("e4-conflict-strat", 4, "Lesson 1 · Theories of Stratification", "Conflict view of stratification",
    "The view that inequality persists because groups with resources and power can protect advantages and shape institutions.",
    "Wealthy groups may influence laws and educational access in ways that reproduce their position.",
    ["Davis–Moore thesis", "Symbolic interactionism", "Modernization theory"],
    "Which perspective emphasizes how powerful groups preserve advantages through institutions?"),
  c("e4-global", 4, "Lesson 1 · Global Inequality", "Global stratification",
    "The unequal distribution of resources, opportunities, and power among nations and regions of the world.",
    "Countries occupy unequal positions in global production, trade, finance, and political influence.",
    ["Domestic social class", "Cultural diffusion", "Urbanization"],
    "Structured inequality among countries and world regions is called what?"),
  c("e4-core-periphery", 4, "Lesson 1 · Global Inequality", "Core, semi-peripheral, and peripheral nations",
    "World-systems categories describing countries' unequal positions in global production, profit, and political power.",
    "Core economies tend to control capital-intensive production, while peripheral economies often supply lower-cost labor or raw materials.",
    ["First, second, and third estates", "Castes", "Primary, secondary, and tertiary groups"],
    "Which categories are used by world-systems theory to describe unequal positions in the global economy?"),
  c("e4-sex", 4, "Lesson 2 · Gender & Sexuality", "Sex",
    "A classification associated with physical and biological traits, while recognizing that biological variation is more complex than a simple binary.",
    "Reproductive anatomy and some physiological traits are commonly used in sex classification.",
    ["Gender", "Gender role", "Sexual orientation"],
    "Which concept refers primarily to classification associated with biological and physical traits?"),
  c("e4-gender", 4, "Lesson 2 · Gender & Sexuality", "Gender",
    "Socially created meanings, identities, expectations, and roles associated with perceived sex categories.",
    "Cultures teach different expectations about appearance, emotion, work, and family responsibilities.",
    ["Sex", "Sexual orientation", "Ethnicity"],
    "Socially created expectations and identities associated with sex categories are called what?"),
  c("e4-gender-identity", 4, "Lesson 2 · Gender & Sexuality", "Gender identity",
    "A person's deeply felt internal sense of gender.",
    "A person's gender identity may or may not correspond with the sex classification assigned at birth.",
    ["Gender expression", "Sexual orientation", "Gender role"],
    "A person's internal sense of gender is called what?"),
  c("e4-expression", 4, "Lesson 2 · Gender & Sexuality", "Gender expression",
    "The outward presentation of gender through appearance, behavior, voice, clothing, or other social signals.",
    "Clothing and mannerisms can communicate gender expression but do not by themselves determine identity or orientation.",
    ["Gender identity", "Sexual orientation", "Biological sex"],
    "The outward presentation of gender through appearance and behavior is called what?"),
  c("e4-orientation", 4, "Lesson 2 · Gender & Sexuality", "Sexual orientation",
    "A person's enduring pattern of romantic or sexual attraction, or lack of attraction, toward others.",
    "Sexual orientation is conceptually different from sex, gender identity, and gender expression.",
    ["Gender identity", "Gender expression", "Sex role"],
    "A pattern of romantic or sexual attraction is referred to as what?"),
  c("e4-doing-gender", 4, "Lesson 2 · Gender & Sexuality", "Doing gender",
    "The idea that gender is repeatedly produced and reinforced through routine interaction and accountability to social expectations.",
    "People may adjust speech, clothing, or household behavior because others evaluate whether it seems gender-appropriate.",
    ["Gender identity", "Gender socialization", "Role exit"],
    "Which concept treats gender as something continually accomplished in everyday interaction?"),
  c("e4-gender-social", 4, "Lesson 2 · Gender & Sexuality", "Gender socialization",
    "The process through which people learn culturally expected gender roles, behaviors, and meanings.",
    "Families, peers, schools, media, religion, and workplaces communicate gender expectations.",
    ["Resocialization", "Gender expression", "Sexual orientation"],
    "Learning a society's gender expectations from family, peers, and media is called what?"),
  c("e4-sexism", 4, "Lesson 2 · Gender & Sexuality", "Sexism",
    "Prejudice, stereotyping, or discrimination based on sex or gender, often embedded in institutional arrangements.",
    "Assuming a person is unsuited for leadership because of gender is sexist.",
    ["Racism", "Classism", "Ethnocentrism"],
    "Discrimination or prejudice based on sex or gender is called what?"),
  c("e4-race", 4, "Lesson 3 · Race & Ethnicity", "Race as a social construction",
    "A socially created classification that assigns meaning to perceived physical differences; categories and meanings vary across societies and history.",
    "A person's racial classification can differ across countries or change as official categories change.",
    ["Race as a fixed biological essence", "Ethnicity", "Nationality"],
    "Racial categories change across time and place even though societies treat them as consequential. This shows race is what?"),
  c("e4-ethnicity", 4, "Lesson 3 · Race & Ethnicity", "Ethnicity",
    "A shared cultural heritage connected to features such as ancestry, language, traditions, religion, or national origin.",
    "People may identify ethnically through shared ancestry, foodways, language, and historical experience.",
    ["Race", "Nationality only", "Social class"],
    "Shared cultural heritage based on ancestry, language, or traditions is called what?"),
  c("e4-minority", 4, "Lesson 3 · Race & Ethnicity", "Minority group",
    "A group whose members experience unequal treatment and reduced power because of socially significant characteristics, regardless of numerical size.",
    "A group can be numerically large yet remain a minority group if it holds less power.",
    ["Numerical minority", "Reference group", "Subculture"],
    "In sociology, what term describes a group disadvantaged by unequal power, even if it is not numerically small?"),
  c("e4-stereotype", 4, "Lesson 3 · Prejudice & Discrimination", "Stereotype",
    "An oversimplified generalization applied to members of a social category.",
    "Assuming every member of an age group has the same technological ability is a stereotype.",
    ["Prejudice", "Discrimination", "Racism"],
    "An oversimplified belief that all members of a category share the same trait is what?"),
  c("e4-prejudice", 4, "Lesson 3 · Prejudice & Discrimination", "Prejudice",
    "A pre-judged attitude or feeling about a group and its members, often based on stereotypes.",
    "Disliking people from a group without knowing them individually is prejudice.",
    ["Discrimination", "Racism", "Segregation"],
    "A negative attitude toward a group is called what?"),
  c("e4-discrimination", 4, "Lesson 3 · Prejudice & Discrimination", "Discrimination",
    "Unequal action or treatment directed at people because of their group membership.",
    "A qualified applicant is denied an interview because of race or gender.",
    ["Prejudice", "Stereotype", "Ethnocentrism"],
    "Unequal treatment of a person because of group membership is called what?"),
  c("e4-racism", 4, "Lesson 3 · Prejudice & Discrimination", "Racism",
    "Beliefs, practices, and arrangements that produce or justify racial hierarchy and unequal outcomes.",
    "Racism can operate through individual behavior, cultural ideas, and institutional systems.",
    ["Prejudice only", "Ethnocentrism", "Assimilation"],
    "Which concept describes beliefs and practices that produce or justify racial hierarchy?"),
  c("e4-institutional", 4, "Lesson 3 · Prejudice & Discrimination", "Institutional discrimination",
    "Policies and routine practices within organizations or systems that create unequal group outcomes, whether or not each actor intends harm.",
    "A facially neutral lending practice may systematically exclude neighborhoods shaped by earlier segregation.",
    ["Individual prejudice", "Cultural relativism", "Pluralism"],
    "Routine organizational practices create unequal racial outcomes without requiring openly prejudiced individuals. What is this?"),
  c("e4-intersectionality", 4, "Lesson 3 · Inequality & Identity", "Intersectionality",
    "An approach examining how overlapping social positions and systems of inequality combine to shape experiences.",
    "The experience of a working-class Black woman cannot always be understood by studying race, class, or gender separately.",
    ["Assimilation", "Status consistency", "Pluralism"],
    "Which approach studies how race, class, gender, and other positions operate together?"),
  c("e4-assimilation", 4, "Lesson 3 · Intergroup Relations", "Assimilation",
    "A process in which a minority group gradually adopts much of the dominant culture and becomes incorporated into it.",
    "Across generations, a family may shift language and customs toward dominant cultural patterns.",
    ["Pluralism", "Segregation", "Expulsion"],
    "Gradual adoption of dominant cultural patterns is called what?"),
  c("e4-pluralism", 4, "Lesson 3 · Intergroup Relations", "Pluralism",
    "A pattern in which distinct groups maintain important cultural differences while participating with relative equality in the larger society.",
    "Communities preserve languages and traditions while sharing political and economic institutions.",
    ["Assimilation", "Segregation", "Amalgamation"],
    "Distinct groups retain cultural traditions while participating with relative equality. What pattern is this?"),
  c("e4-segregation", 4, "Lesson 3 · Intergroup Relations", "Segregation",
    "The physical and social separation of groups, imposed by law or produced through social practices and unequal opportunities.",
    "Housing patterns may remain separated even after explicit segregation laws are removed.",
    ["Assimilation", "Pluralism", "Amalgamation"],
    "The social and physical separation of groups is called what?"),

  // EXAM 5 — SOCIAL INSTITUTIONS
  c("e5-power", 5, "Lesson 1 · Government & Politics", "Power",
    "The ability to get others to act in a desired way, even when they resist.",
    "A government compels compliance through law, while an employer influences behavior through control of workplace rewards.",
    ["Authority", "Legitimacy", "Prestige"],
    "The ability to carry out one's will despite resistance is called what?"),
  c("e5-authority", 5, "Lesson 1 · Government & Politics", "Authority",
    "Power regarded as legitimate by those who are expected to obey.",
    "People follow a judge's courtroom directions because the position is recognized as having lawful authority.",
    ["Coercion", "Prestige", "Influence"],
    "Power that people accept as rightful or legitimate is called what?"),
  c("e5-traditional", 5, "Lesson 1 · Types of Authority", "Traditional authority",
    "Legitimate power grounded in long-established customs, inherited positions, or sacred traditions.",
    "A hereditary monarch claims the right to rule through established tradition.",
    ["Charismatic authority", "Legal-rational authority", "Bureaucratic power"],
    "A ruler's legitimacy rests on inherited custom. Which type of authority is this?"),
  c("e5-charismatic", 5, "Lesson 1 · Types of Authority", "Charismatic authority",
    "Legitimate power based on followers' devotion to a leader they regard as extraordinary or inspiring.",
    "Supporters obey a movement leader because they believe the leader has exceptional personal qualities.",
    ["Traditional authority", "Legal-rational authority", "Coercive power"],
    "Followers accept a leader because of perceived extraordinary personal qualities. Which authority type applies?"),
  c("e5-legal", 5, "Lesson 1 · Types of Authority", "Legal-rational authority",
    "Legitimate power grounded in formal rules, laws, and offices rather than a specific person's identity.",
    "A public official has authority because law defines the powers of the office.",
    ["Traditional authority", "Charismatic authority", "Informal influence"],
    "Authority attached to a legally defined office is which type?"),
  c("e5-democracy", 5, "Lesson 1 · Government", "Democracy",
    "A political system in which the population participates in selecting leaders and influencing collective decisions, directly or through representatives.",
    "Citizens vote in competitive elections and can organize to influence public policy.",
    ["Monarchy", "Oligarchy", "Totalitarianism"],
    "Which political system locates governing legitimacy in participation by the people?"),
  c("e5-oligarchy", 5, "Lesson 1 · Government", "Oligarchy",
    "A political system in which a small, powerful group controls government.",
    "A narrow circle of wealthy families or military leaders dominates political decision-making.",
    ["Democracy", "Monarchy", "Anarchy"],
    "Rule by a small and powerful group is called what?"),
  c("e5-pluralist", 5, "Lesson 1 · Political Perspectives", "Pluralist model",
    "The view that political power is dispersed among many competing groups, none of which controls every issue.",
    "Labor, business, environmental, religious, and neighborhood groups compete to influence policy.",
    ["Power-elite model", "Traditional authority", "Totalitarian model"],
    "Which model sees political power as distributed among many competing interest groups?"),
  c("e5-power-elite", 5, "Lesson 1 · Political Perspectives", "Power-elite model",
    "The view that a relatively small network of leaders in major economic, political, and military institutions holds disproportionate power.",
    "Top corporate and government decision-makers may move through overlapping institutions and social networks.",
    ["Pluralist model", "Functionalist model", "Democratic-participation model"],
    "Which model argues that a small institutional elite holds disproportionate political power?"),
  c("e5-capitalism", 5, "Lesson 1 · Economy & Work", "Capitalism",
    "An economic system based mainly on private ownership, market exchange, competition, and production for profit.",
    "Most businesses are privately owned and make production decisions in response to markets.",
    ["Socialism", "Communism", "Mercantilism"],
    "Private ownership and production for profit are central to which economic system?"),
  c("e5-socialism", 5, "Lesson 1 · Economy & Work", "Socialism",
    "An economic system in which major productive resources are collectively or publicly controlled to pursue social provision and reduced inequality.",
    "Public ownership or strong social control may guide key industries and distribution.",
    ["Capitalism", "Feudalism", "Mercantilism"],
    "Collective or public control of major productive resources is associated with which system?"),
  c("e5-globalization", 5, "Lesson 1 · Economy & Work", "Economic globalization",
    "The growing integration of production, trade, finance, and labor across national borders.",
    "A product is designed in one country, assembled in another, and sold worldwide through a multinational firm.",
    ["Outsourcing", "Industrialization", "Localization"],
    "The increasing cross-border integration of production and markets is called what?"),
  c("e5-outsourcing", 5, "Lesson 1 · Economy & Work", "Outsourcing",
    "Contracting work previously performed within an organization to an outside organization, domestically or abroad.",
    "A company hires another firm to operate its customer-service center.",
    ["Automation", "Underemployment", "Globalization"],
    "A company transfers an internal task to an outside contractor. What is this called?"),
  c("e5-alienation", 5, "Lesson 1 · Economy & Work", "Alienation",
    "Marx's concept for workers' separation from their labor, its products, other workers, and a sense of human creativity or control.",
    "A worker repeats a tightly controlled task but has no say in the process and no connection to the finished product.",
    ["Anomie", "Role strain", "Rationalization"],
    "A worker lacks control over the labor process and feels disconnected from the product. Which concept applies?"),
  c("e5-underemployment", 5, "Lesson 1 · Economy & Work", "Underemployment",
    "Employment that provides fewer hours than desired or does not adequately use a worker's skills and training.",
    "A trained engineer can find only part-time work unrelated to engineering.",
    ["Unemployment", "Structural mobility", "Outsourcing"],
    "A skilled worker has only involuntary part-time work far below their training. What is this?"),
  c("e5-education", 5, "Lesson 2 · Education", "Education as a social institution",
    "The organized system through which society transmits knowledge, skills, culture, and social expectations.",
    "Schools teach academic content while also socializing students into schedules, evaluation, and group participation.",
    ["Education as only personal achievement", "Informal economy", "Primary group"],
    "Which institution formally transmits knowledge, skills, and cultural expectations across generations?"),
  c("e5-formal-education", 5, "Lesson 2 · Education", "Formal education",
    "Intentional, structured learning delivered through recognized schools, curricula, and credentials.",
    "A student completes scheduled courses leading to a college degree.",
    ["Informal education", "Hidden curriculum", "Cultural transmission"],
    "Structured learning through schools and recognized credentials is called what?"),
  c("e5-hidden", 5, "Lesson 2 · Education", "Hidden curriculum",
    "Unstated lessons schools communicate about behavior, hierarchy, competition, discipline, and social expectations.",
    "Students learn punctuality and deference to schedules even when those are not listed as course content.",
    ["Formal curriculum", "Credentialism", "Tracking"],
    "Unwritten lessons about punctuality, competition, and obedience form the what?"),
  c("e5-cultural-capital", 5, "Lesson 2 · Education", "Cultural capital",
    "Socially valued knowledge, language styles, habits, and tastes that can help people succeed in institutions.",
    "Familiarity with how to communicate with professors or navigate college procedures can create an advantage.",
    ["Human capital", "Social mobility", "Credentialism"],
    "Institutionally valued styles of speech, knowledge, and behavior are called what?"),
  c("e5-tracking", 5, "Lesson 2 · Education", "Tracking",
    "The placement of students into different academic paths or ability groups that provide unequal learning opportunities.",
    "Students assigned early to lower-level courses may receive less demanding content and fewer later options.",
    ["Sorting", "Credentialism", "Social promotion"],
    "Assigning students to different academic pathways based on perceived ability is called what?"),
  c("e5-credentialism", 5, "Lesson 2 · Education", "Credentialism",
    "Increasing reliance on degrees and certificates as proof of qualification, sometimes beyond what a job's tasks require.",
    "An employer begins requiring a bachelor's degree for work previously performed without one.",
    ["Cultural capital", "Tracking", "Hidden curriculum"],
    "Requiring additional degrees as screening devices, even when job duties have not changed, illustrates what?"),
  c("e5-religion", 5, "Lesson 2 · Religion", "Religion",
    "A social institution involving beliefs and practices through which communities address the sacred and create meaning.",
    "Religious communities use rituals, symbols, narratives, and moral teachings to organize shared life.",
    ["Culture only", "Magic", "Ideology only"],
    "A social institution built around shared beliefs and practices concerning the sacred is what?"),
  c("e5-sacred-profane", 5, "Lesson 2 · Religion", "Sacred and profane",
    "Durkheim's distinction between things set apart as extraordinary or holy and things belonging to ordinary everyday life.",
    "An object becomes sacred because a community separates it from ordinary use and invests it with special meaning.",
    ["Religious and secular", "Church and sect", "Faith and ritual"],
    "Which distinction separates things treated as holy from ordinary everyday things?"),
  c("e5-religion-function", 5, "Lesson 2 · Religion", "Functionalist view of religion",
    "The view that religion can create solidarity, meaning, moral guidance, and support during major life transitions.",
    "Shared rituals reinforce group identity and help people respond collectively to loss.",
    ["Conflict view of religion", "Interactionist view of religion", "Secularization"],
    "Which perspective emphasizes religion's contribution to social cohesion and shared meaning?"),
  c("e5-religion-conflict", 5, "Lesson 2 · Religion", "Conflict view of religion",
    "The view that religion may legitimize inequality, support dominant groups, or become a site of struggle and social change.",
    "A doctrine may be used to justify an unequal hierarchy, while religious movements may also challenge power.",
    ["Functionalist view of religion", "Interactionist view of religion", "Secularization"],
    "Which perspective asks whether religion reinforces inequality and whose interests it serves?"),
  c("e5-secularization", 5, "Lesson 2 · Religion", "Secularization",
    "A process through which religious authority or participation declines in some areas of social life.",
    "Government and education may become less directly controlled by religious institutions over time.",
    ["Fundamentalism", "Religious revival", "Pluralism"],
    "Declining religious institutional control over public life is called what?"),
  c("e5-med-soc", 5, "Lesson 3 · Health & Medicine", "Medical sociology",
    "The sociological study of health, illness, healthcare systems, and the social forces that shape them.",
    "A study examines how class, race, work, housing, and insurance affect access to care.",
    ["Epidemiology", "Clinical medicine", "Public health only"],
    "Which field studies health and healthcare as social phenomena?"),
  c("e5-social-construction-health", 5, "Lesson 3 · Health & Medicine", "Social construction of health",
    "The idea that societies shape how conditions are defined, interpreted, labeled, and responded to as health or illness.",
    "The same condition may carry different meanings, stigma, or institutional responses across time and cultures.",
    ["Biological determinism", "Epidemiology", "Medicalization"],
    "Changing cultural definitions of what counts as illness demonstrate which sociological idea?"),
  c("e5-epidemiology", 5, "Lesson 3 · Health & Medicine", "Social epidemiology",
    "The study of how disease, injury, and health outcomes are distributed across populations and shaped by social conditions.",
    "Researchers compare illness rates by neighborhood, income, occupation, race, and gender.",
    ["Medicalization", "Sick role", "Clinical diagnosis"],
    "Studying how health outcomes vary by class, neighborhood, race, and occupation is called what?"),
  c("e5-determinants", 5, "Lesson 3 · Health & Medicine", "Social determinants of health",
    "The social and economic conditions influencing exposure to risks, access to resources, and opportunities for health.",
    "Income, housing, education, transportation, work conditions, food access, discrimination, and neighborhood safety affect health.",
    ["Genetic determinants", "Medicalization", "Sick role"],
    "Housing, transportation, income, education, and work conditions are examples of what?"),
  c("e5-health-disparity", 5, "Lesson 3 · Health & Medicine", "Health disparity",
    "A patterned and avoidable difference in health outcomes or healthcare access between social groups.",
    "One racial or income group experiences higher preventable illness because it faces unequal conditions and care.",
    ["Random health variation", "Medicalization", "Morbidity only"],
    "A systematic, avoidable group difference in health outcomes is called what?"),
  c("e5-stigma", 5, "Lesson 3 · Health & Medicine", "Stigma",
    "A deeply discrediting social label that marks a person as undesirable and can produce exclusion or discrimination.",
    "Someone avoids treatment because they fear being labeled negatively for a mental-health condition.",
    ["Sick role", "Medicalization", "Prevalence"],
    "A discrediting label attached to an illness leads to shame and exclusion. Which concept applies?"),
  c("e5-medicalization", 5, "Lesson 3 · Health & Medicine", "Medicalization",
    "The process through which a condition or behavior becomes defined and treated as a medical problem.",
    "A behavior once treated mainly as a moral failure comes to be diagnosed and treated clinically.",
    ["Stigmatization", "Social epidemiology", "Demography"],
    "A nonmedical behavior comes to be defined, diagnosed, and treated as an illness. What process is this?"),
  c("e5-sick-role", 5, "Lesson 3 · Health & Medicine", "Sick role",
    "Parsons's concept describing socially recognized rights and obligations attached to being legitimately ill.",
    "A sick person may be excused from ordinary duties but is expected to seek help and try to recover.",
    ["Patient role", "Medicalization", "Stigma"],
    "Being excused from normal duties while expected to seek care and recover describes what?"),
  c("e5-healthcare-types", 5, "Lesson 3 · Health & Medicine", "Private, public, and universal healthcare",
    "Private systems rely heavily on privately financed coverage; public systems use government financing or provision; universal systems aim to cover all residents.",
    "A country can provide universal access through different combinations of public financing and private delivery.",
    ["Primary, secondary, and tertiary care", "Acute, chronic, and preventive care", "Formal, informal, and hidden healthcare"],
    "Which distinction classifies healthcare by financing, provision, and whether all residents are covered?"),
  c("e5-institution-link", 5, "Lesson 3 · Institutions in Context", "Interdependence of social institutions",
    "The idea that changes in one institution produce consequences in others because institutions operate as connected parts of society.",
    "Job loss in the economy can alter family stress, health access, school enrollment, and political demands.",
    ["Institutional isolation", "Cultural relativism", "Role exit"],
    "Economic change affects family life, education, health, and politics. Which broad sociological idea does this illustrate?")
];

Object.freeze(EXAM_INFO);
Object.freeze(SOC105_CARDS);
